CREATE TABLE [dbo].[Menus]
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()) NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,
	CreationDate DATETIME NOT NULL,
	ModifiedDate DATETIME NULL,
	ModifiedUserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NULL,
	Active BIT DEFAULT(1) NOT NULL
)
