CREATE TABLE [dbo].[Reservations]
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()) NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,
	CreationDate DATETIME NOT NULL,
	ModifiedDate DATETIME NULL,
	Active BIT DEFAULT(1) NOT NULL
)
