CREATE TABLE [dbo].[UserRoles]
(
	UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	RoleId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Roles(Id) NOT NULL,
	PRIMARY KEY (UserId, RoleId)
)
